apiVersion: batch/v1
kind: Job
metadata:
  name: dk-training-job
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: dk-training-job
          image: europe-west4-docker.pkg.dev/actin-build/build-registry-docker/denis-kumar-gcp-training:0.0.1          
          imagePullPolicy: Always
      restartPolicy: OnFailure
