apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-subscriber-deployment-dk
  namespace: default
  labels:
    app: pubsub-subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-subscriber
  template:
    metadata:
      labels:
        app: pubsub-subscriber
    spec:
      serviceAccountName: pubsub-workload-sa
      containers:
        - name: pubsub-subscriber-deployment-dk
          image: europe-west4-docker.pkg.dev/actin-build/build-registry-docker/denis-kumar-gcp-training-sub:0.0.1
          imagePullPolicy: Always
      restartPolicy: Always